# Generated by Django 3.2.22 on 2025-04-20 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(choices=[(1, 'Alphabet Signs'), (2, 'Numbers Signs'), (3, 'Common Words Signs')], help_text='Select the chapter this video belongs to')),
                ('title', models.CharField(help_text='Title of the video', max_length=200)),
                ('description', models.TextField(help_text='Description of the video content')),
                ('video_file', models.FileField(help_text='Upload video file (mp4, webm, or ogg)', upload_to='dictionary/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])])),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail image for the video', null=True, upload_to='dictionary/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['chapter', 'created_at'],
            },
        ),
    ]
